

#FROM gcr.io/jt17383-research/gym:gym
FROM ufoym/deepo:tensorflow-py36-cu100
WORKDIR /root
RUN pip install tensorflow google-cloud-storage gym keras sklearn
#WORKDIR /root
RUN mkdir -p xdrl/nchain
COPY agents xdrl/nchain
COPY gcloud_auth.json xdrl
RUN echo 'export GOOGLE_APPLICATION_CREDENTIALS="gcloud_auth.json"' >> .bashrc
WORKDIR /root/xdrl

# Set up the entry point to invoke the trainer.
ENTRYPOINT ["python", "-m", "nchain.agent"]
